### ISSUE TITLE
Don't allow adding both Secure API and Preview API keys

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-swift#47]
### Motivation

It should be apparent to the developer that the two keys can't be combined.

### Proposed solution

Throw an exception/log an error in the constructor...

**Comment by sagarchoudhary96** [comment]
heey @petrsvihlik can i pick up this issue?

**Comment by makma** [comment]
Hi, thank you for your interest. Sure you can! I've just sent you an invitation and assigned you the task. Welcome to Kentico Community!

**Comment by sagarchoudhary96** [comment]
thanks @makma , i'll start working to it and send PR soon.

**Comment by sagarchoudhary96** [comment]
@makma  is there any slack/gitter channel for kenticoo where i can join and ask if i have any concern.

**Comment by sagarchoudhary96** [comment]
@makma what should be the error show. is `Both secure API and preview API keys cannot be combined. pass only one key.` correct or need to modify something in it.

**Comment by petrsvihlik** [comment]
hi @sagarchoudhary96 

- gitter: https://gitter.im/Kentico/Kontent
- validation message: we use the following in the .net SDK:

https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/Builders/DeliveryOptions/DeliveryOptionsValidator.cs#L140

**Comment by sagarchoudhary96** [comment]
@makma i have raised PR for this one.
