### ISSUE TITLE
Add modular_content dictionary as a mapping option

### ISSUE THREAD

**Issue by leeprobert** [Kentico/kontent-delivery-sdk-swift#71]
When retrieving LinkedItemsElement objects in a custom class, there is no way to ascertain the content types for each of the linked elements. The value is just an array of the codenames. One way around this is to allow the user to create a custom mapping of the "modular_content" dictionary from the JSON.

Here is an example of how you might do this: https://www.evernote.com/l/AAQueEsu1JpLrZZDEk7i5TgcOV5Dm04yf7QB/image.png
![FeaturedItems_swift](https://user-images.githubusercontent.com/151336/60654083-3161c800-9e43-11e9-8f41-8e17c03fd801.jpg)

**Comment by leeprobert** [comment]
This is possibly where you could add the dictionary: https://www.evernote.com/l/AATyPWNIiBdJIZVnFn-gyNrWmLxCPFgtCagB/image.png
![ItemsResponse_swift](https://user-images.githubusercontent.com/151336/60654713-6d495d00-9e44-11e9-8b1c-d5ca7db38629.jpg)

**Comment by makma** [comment]
Hi @leeprobert, this is totally a valid scenario as well as a feature request. I'll do my best to implement it next week, however, if you/whoever have a working prototype/code feel free to create a pull request. Thank you.

**Comment by makma** [comment]
Hello, in https://github.com/Kentico/kontent-delivery-sdk-swift/pull/93 I've changed the visibility of the `map` for `itemResponse` and `itemsReponse`. These codenames can be now mapped to items: 
 `let modularContent = itemResponse?.map.JSON["modular_content"] as! [String : AnyObject]`. I believe  this might also be a fix to this issue. This is available in `v2.2.2`.
