### ISSUE TITLE
Realm support for caching

### ISSUE THREAD

**Issue by leeprobert** [Kentico/kontent-delivery-sdk-swift#72]
I wonder if we could support Realm and therefore caching and offline mode for our apps?
We'd need to intercept the mapping to objects and check if the object already exists in the Realm DB. If it does, there'd be a check for equatability, and a possible update of properties to keep everything in sync. Otherwise the object gets created as normal but also stored in Realm.

**Comment by makma** [comment]
If I understand you correctly, you should conform [Hashable](https://developer.apple.com/documentation/swift/hashable) (and Mappable) protocol for your model class. As you conform to it, you must [implement](https://stackoverflow.com/questions/34705786/swift-how-to-implement-hashable-protocol-based-on-object-reference) `hashValue` property or `hash(..)` function (depending on your swift version). Once you have a hash function for your strongly typed object obtained from the Kentico Cloud, you can use this hash value as an identifier/cache key for your Realm/any other cache persistent layer. Does this suit your need?

However, all this logic should be IMO placed in the wrapper around the `getItem()` or `getItems()` functions and shouldn't be part of the SDK.
